# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0005_idttestpropertyestimate_detection_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idttestpropertyestimate',
            name='estimate_label',
            field=models.CharField(max_length=255),
        ),
    ]
