# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0008_remove_idtdiagnostictest_selected_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1st_gen_lab', '1st Gen Lab Assay (Viral Lysate IgG sensitive Antibody)'), ('2nd_gen_lab', '2nd Gen Lab Assay (Recombinant IgG sensitive Antibody)'), ('2nd_gen_rapid', '2nd Gen Rapid Test'), ('3rd_gen_lab', '3rd Gen Lab Assay (IgM sensitive Antibody)'), ('3rd_gen_rapid', '3rd Gen Rapid Test'), ('4th_gen_lab', '4th Gen Lab Assay (p24 Ag/Ab Combo)'), ('4th_gen_rapid', '4th Gen Rapid Test'), ('dpp', 'DPP'), ('immunofluorescence_assay', 'Immunofluorescence Assay'), ('p24_antigen', 'p24 Antigen'), ('viral_load', 'Viral Load'), ('western_blot', 'Western blot')], max_length=255, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infection_dating_tool.IDTDiagnosticTest')),
                ('user', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selectedcategory',
            unique_together=set([('user', 'test')]),
        ),
    ]
