# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0010_growthrateestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infection_dating_tool.IDTDiagnosticTest')),
                ('user', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selectedtest',
            unique_together=set([('user', 'test')]),
        ),
    ]
