# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-27 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0011_auto_20170511_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectiousPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infectious_period', models.FloatField()),
                ('infectious_period_input', models.FloatField(null=True)),
                ('viral_growth_rate', models.FloatField(null=True)),
                ('origin_viral_load', models.FloatField(null=True)),
                ('viral_load', models.FloatField(null=True)),
                ('user', lib.fields.OneToOneOrNoneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idt_infectious_period',
            },
        ),
    ]
