# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0014_auto_20170629_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectiousperiod',
            name='graph_file',
            field=models.FileField(max_length=255, null=True, upload_to='graphs'),
        ),
        migrations.AlterField(
            model_name='idtfileinfo',
            name='data_file',
            field=models.FileField(upload_to='/home/andrew/id/infection-dating-tool/cephia/cephia/../../media/infection_dating_tool_uploads'),
        ),
    ]
