# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0017_idttestpropertyestimate_diagnostic_delay_sigma'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariabilityAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_factor', models.FloatField(default=1.0, verbose_name='Intersubject variability adjustment factor (SDs)')),
                ('user', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='growthrateestimate',
            unique_together=set([('user', 'growth_rate')]),
        ),
        migrations.AlterUniqueTogether(
            name='variabilityadjustment',
            unique_together=set([('user', 'adjustment_factor')]),
        ),
    ]
