# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0018_auto_20170706_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infectiousperiod',
            old_name='graph_file',
            new_name='graph_file_probability',
        ),
        migrations.AddField(
            model_name='infectiousperiod',
            name='graph_file_donations',
            field=models.FileField(max_length=255, null=True, upload_to='graphs'),
        ),
    ]
