# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 09:14
from __future__ import unicode_literals

from django.db import migrations

def create_global_residual_risk(apps, schema):
    ResidualRiskModel = apps.get_model("infection_dating_tool", "ResidualRisk")
    ResidualRiskModel.objects.create(
        infectious_period=-7.7113428695314825,
        viral_growth_rate=0.35,
        origin_viral_load=1.0,
        viral_load=0.002
    )


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0020_auto_20170913_1739'),
    ]

    operations = [
        migrations.RunPython(create_global_residual_risk, migrations.RunPython.noop)
    ]
