# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-15 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0022_auto_20170913_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariabilityAdjustment',
            new_name='CredibilityInterval',
        ),
    ]
