# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0024_auto_20181115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtdiagnostictesthistory',
            name='sigma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
