# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0025_idtdiagnostictesthistory_sigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtdiagnostictesthistory',
            name='warning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
