* notes from meeting 03/11
** new output reports
Eduard will give us a list of the new reports

** tests
eddi system should have tests

** generic assay
# Eduard might send an example
# will be named (not generic)
# create new table with name field
copy duke table (not everything)



** tasts to be completed
Eduard will provide a list of most essential issues
*** complete this list properly with status of each task
    outside eddi
    assay runs
    volume calculation
    shipments
    tests

** get outside_eddi ready for Tuesday

generic results produces one row per specimen
other exports full results (looks in specific assay results table)
make available both result queries

** runs - important
assay runs: change tab name to assay results
change filter to allow the user to filter by visit or upload list of visits or list of specimens or say show all visits with data on the selected assays
add run id to export
export generic or full
user visits form
kill delete run button - change permissions for different users / add confirm button
when permission is added - not available by default to new user (Eduard must add permission to users)

issues
take out visit id for combine assay results for visits block
add panel membership filter - if they do not select panel membership then export all results for all panels
add specimen filter (copy specimen filter from visit filter form)
if they do not select anything before selecting get results then export everything

** file upload/download page
if admin you can upload or download or delete files
other users can view files


** eddi calculation
save map for a file and set of results so that the user can review the map used for a result output (save and export file map for later use)

** eddi results
Subject	EP DDI	LP DDI	Interval Size	EDDI
provide export csv
* notes from meeting 10/11
<<<<<<< HEAD
** full results export - this needs to happen first
add visit foreign key to results for both specific and generic tables
add filter by visits option

remove test mode for final results lines
why is my export giving two copies of the final results?
make sure that you can export generic and full results
** outside eddi - this happens next
*** user registration + catch
make sure that people cannot spam user registrations (capture?)
ensure that a logged in user cannot access the main site
*** visual changes
leave login screen images at the bottom but change the Sacema logo at the top to Cephia logo
change app name to Cephia Infection Dating Tool and welcome message to welcome to...
add banner with logo and app name to the top of the screen above the screen tabs

copy banner and tabs from main site

- drop EDDI and home - replace with image and Cephia Infection Dating Tool at the top, same as Cephia site (clicking on logo link takes you to data files page)
- add help tab to help page
- change data files to landing page/home page
- cephia will provide helpful paragraph for landing page
*** data file
change to just subject, date, test, result
possibly provide example file on help page
only accept csv files. dates can be a problem in excel
change verification errors - change to pop up that needs the user to click okay on without any fade away (add disclaimer file not saved)
change the file to save data to table automatically - remove save data link because this happens automatically
change mapping requirement notifaction - do not need line by info on mapping needed - just say mapping needed
change provide and review mapping to just mapping
remove message column from table
ensure that all data for the file is deleted along with the file - change x to purge button so that it is clear what the user is doing

*** mapping
why can I not add new map called new code?
preselect default property for a test when adding a new map or editing - each time you change the test - add user defaults to their own tests
when a map code is changed then clicking on the mapping link for a file should replace with a new map for that code to replace it

** github user for R server
create new user with read access only for the server to deal with this
cephia-deploy
do we need to be logged in to read only? if so then we need to create an email address

** add assay imports (do first)
provide assay name
define assay
gets added to list of assays
fields
- recent
- non recent
- possibly more? check what duke accepts

generic file handler for results
(copy code from bioplex duke)
=======
>>>>>>> sprint16
=======
* notes from meeting 17/11
mysql optimizer
>>>>>>> meeting_branch
* notes from meeting 22/11
** small new feature for filter
background clinical data
filter by specimen and visits
supress results, there could be more than one and they are not looking for results with this filter
** flip order of files and custom asssay tabs
** change column order
generic id
specific id
visit id
specimen id
subject id
specimen label
(order by subject id, visit id, specimen id, generic id, specific id)



** change preview limit to 25
** remove hard limit for result output
explore more efficient ways of producing everything
if result output exceeds a certain amoutn then prompt the user to confirm that they want to export such a large amout of data.
another option would be to put a promt for the user to confirm when the form has no values (i.e. when it would return everything)
** can we move data and system over to postgres?
** outside eddi
change url name, etc. no more outside eddi
** outside eddi
possibly add a tooltip over column header explaining different states for files
add a bit of a white space between choose file and upload
change message about mapping 'Please provide mapping for your file'

make sure that files are processed in the background

when clicking on mapping then the system checks the maps for the file (possibly store a list of unique codes in a file to check against rather than having to query everything)
this also happenes every time the mapping page is loaded for a file. needs to be improved a lot

possibly add a button to the file mapping page which allows the user to confirm the mapping to be completed. remove function call on page load, etc
will possibly need to save unique subjects at the same time

* call with Eduard 29/11
with all result downloads
viral load offset (num days between) negative number if viral load is before current visit or positive if viral load is after.

if viral load is null and there is a visit within 30 days before or 30 days after with a viral load. get the viral load from the other visit
if there is a visit before or after 

if there is more than one visit within the 30 day range then take closest. only grab a viral load from a different visit if the treatment status is the same as the current visit. reports offset.
always report viral load off set, defaults to 0 when viral load is from the current visit.


management command that calculates the numeric viral load - add this to the command if vl is null
* notes from meeting 01/12
** vl update
if there is an earlier and later date equally distant, which do we use?
*** check the reason for all lines failing
most recent visit file uploaded (leading zero dropped off subject labels)
**** error log
***** columns
Your file contained the following extra columns 
and they have been ignored [u'VISIT_Date', u'notes', u'pendingspecimenmatch']

***** validate
ERROR 2016-12-02 10:29:34,222 4289 visit_file_handler.py 124: Visit already exists.
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 93, in validate
    raise Exception("Visit already exists.")
Exception: Visit already exists.
ERROR 2016-12-02 10:29:37,077 4289 visit_file_handler.py 124: Visit already exists.
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 93, in validate
    raise Exception("Visit already exists.")
Exception: Visit already exists.
ERROR 2016-12-02 10:29:37,551 4289 visit_file_handler.py 124: 'visitdate'
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 90, in validate
    already_exists = Visit.objects.filter(subject_label=visit_row.subject_label, visit_date=self.registered_dates['visitdate']).exists()
KeyError: 'visitdate'
ERROR 2016-12-02 10:29:37,589 4289 visit_file_handler.py 124: 'visitdate'
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 90, in validate
    already_exists = Visit.objects.filter(subject_label=visit_row.subject_label, visit_date=self.registered_dates['visitdate']).exists()
KeyError: 'visitdate'
ERROR 2016-12-02 10:29:37,622 4289 visit_file_handler.py 124: 'visitdate'
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 90, in validate
    already_exists = Visit.objects.filter(subject_label=visit_row.subject_label, visit_date=self.registered_dates['visitdate']).exists()
KeyError: 'visitdate'
ERROR 2016-12-02 10:29:37,656 4289 visit_file_handler.py 124: 'visitdate'
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 90, in validate
    already_exists = Visit.objects.filter(subject_label=visit_row.subject_label, visit_date=self.registered_dates['visitdate']).exists()
KeyError: 'visitdate'
ERROR 2016-12-02 10:29:37,691 4289 visit_file_handler.py 124: 'visitdate'
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 90, in validate
    already_exists = Visit.objects.filter(subject_label=visit_row.subject_label, visit_date=self.registered_dates['visitdate']).exists()
KeyError: 'visitdate'
Unknown command: 'validate_imported_files2'
Type 'manage.py help' for usage.

***** process
ValueError: invalid literal for int() with base 10: '3<L'
ERROR 2016-12-02 11:05:18,023 4916 visit_file_handler.py 166: (1048, "Column 'artificial' cannot be null")
Traceback (most recent call last):
  File "/home/andrew/id/cephia/cephia/cephia/file_handlers/visit_file_handler.py", line 154, in process
    artificial = self.get_bool(visit_row.artificial)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 117, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/andrew/id/cephia/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'artificial' cannot be null")


** cephia infection dating tool
set up result download via csv.
hide/remove variability and median from properties
change mean name to something more descriptive
enlarge modals for extra room
user test property default not selected when mapping?
file notifications are not popping up on staging server?
*** categorise tests for test ordering, etc
2nd gen
3rd gen
4th gen
rapid tests
NAT/viral load
supplemental assay
share mapping/add to global tests.
add user groups for multiple users to use same codes, etc.

add an additional result type, pos, neg, indeterminate (important)



* notes from meeting 08/12
two recomendations
- do not allow 

change email link text. 'Follow this link to complete your registration'
fix file name to not include directory on result download
change results export name to 'infection_dates_file_name_date'

under global test - show default test as a different colour/font colour or bold. on the edit test page

help page - index for page headers with links

is there an easy/safe django way to change all field names.

filter generic only showing one result when not selecting anything in the assay results filter

** mail server setup
is iRedMail the best option for only sending mail
use send mail (django plug)
install send mail possibly
use django send mail plugin

test most basic setup on a gmail and exchange/outlook mail (Alex has one)
google does gmail drop mails from sub-domain

have a 'haven't received an email? do this...' link on the registration page
domain must be cephiadb.incidence-estimation.org

drop footer

** other server
what is backup protocol?
what is security update protocol?


** old issues notes
*** 601 estimate type
this issue can be closed, nothing needs doing.
*** issue103 Integrate the panel model tables
drop
*** issue134 Create assay lookup
drop
*** issue532 install the existing CMS django onto the new server
not likely to happen
*** issue581 Panel Memberships
investigate the QP and EP scripts. can we do this easily?
*** issue583 reverse engineering panel memberships
look at issue above
*** issue585 Shipments
on hold until further notice
*** issue587 Public facing data
will be dealt with middle of next year
*** issue588 single website
drop
*** issue595 diagnostic script for checking volume counts
on hold for now but make sure that the file handler update is pushed to live
*** issue586 Testing
put on hold



** row_info pages
how does the system know which row info page to insert in table_header block, etc?
It seems that it is not always loading the correct page.
* notes from meeting 09/12
** cephia infection dating tool
keep extra characters at end of file names to distringuish which is which
** row_info pages
only seems to be affecting assay results. there are more than one assay file type, perhaps this adds to the confusion.
** file_info filter
update file type list to include all file types.
** registration help link
** test property defaults
why does it say default property? this should be a hidden form field.
Change properties header to be bolder
use colour, not bold.
provide reason why colour
** run results
make the extra visit tables above the results default to collapsed

*** are we doing these?
** result downloads
add generic/final result to wide/raw result export i.e. for each wide result row, provide the generic result row on the next line
** preview detailed results
can we load on html page?


** possibly provide an excel file output of all tests and test properties for cephia
they need to review names, descriptions, etc.
could I provide an option to export this to excel?
possibly provide a mamangement command so that they can re-use the code

* notes from call with Eduard 13/12
custom assay results export is showing recent in some result_field rows, recent is a result value, not a result field.
* notes from meeting 14/12
** filter by specimens
create another version of the assay run filter by visit for Visit queryset.
we can upload specimen labels or visit ids. (for now just specimen labels)

this will filter the Visit objects and provide all related data
add to specimens page the same as the filter on the assay results page.
filter by:
specimen label
panels

provide an export that uses the same columns as the results export (possibly only clinical columns)

** volume counts scripts
for each root specimen find all rows in the bellow the line table that reported against speciment label/type combination
add up all volumes from bellow the line (volume value times number of containers) for each row bellow the line.
figure out if there was a re-reporting error in which some rows were rejected. if this happened then were any of the bellow the line rows rejected?

- write a script which looks for all the bellow the line rows for the specimen label/type combination (these could be from more than one file).
- check with each batch of rows what the total container count and volume should be (i.e. number of containers x volume for each row, added together)
- does the reported volume and number of containers match the result of this calculation? if not then add message with specimen label and id and volume not matching expected
values to the message log.
- if any of the rows had an error message then add a message with the error, specimen label and id. (these are the most likely to fail the volume calculation)

** test and test properties export
do this.

** send_mail
can we use local host?
* noets from meeting 18/01
commit 570534521d289eed1ccb707b33bbbf860f98a8a2
* notes from meeting 19/01
** issues
*** main site
shipments - kill
public facing data - on hold
issue532 install the existing CMS django onto the new server - kill
tests - hold - fix last test or comment out
volume counts - needs to be done, waiting on Eduard's instruction (check current handling of volumes, should be correct)
field names (can change db field name on model) - Eduard can let me know which fields he wants changed
wide/raw results download - kill

panel memberships - look at generic results
find unique id for each specimen
look at one assay run, find all visits and how many times
for each unique visit, create panel membership and how many times
visit id and number of times that it occurs in the panel

R shiny apps
make sure that the guy who wrote the R code is set up for deploying new code
might sub-contract a guy

filter and download specimens - name will be changed (check that all fields are the same as result download, even if invalid)

status of outstanding assays
will be given a list

extracting data
will be given details once Eduard and Alex have looked over what might still need to be done

new issues:
blinded subject id - new field?


*** cephia infection dating tool
**** mail
use gmail for send mail - get final name (no_reply_cephia_eddi_tool@gmail.com) might use a gmail account which uses a different domain. if no cost then use this
instead of gmail.

**** update tests and properties
now a manual input rather than import from main site

tests:
new names
test category (organise by category) - add headers to table for categories


properties:
only default properties - name cephia estimate
drop reference and description for comment field
add field standard error mean diagnostics delay
update display names for fields

fields:
name
mean
mean delay
comment

**** help page and link
will receive from Eduard and Alex

**** possible future feature
ind - tests must be set to accept or not
tests have indeterminate allowed

**** styling
show which tab you are currently on - possibly make it look like the main site navigation

add a link to the help page for non logged in users to view before signing up. probably
hide navigation bar, etc from users not logged in

** notes from Alex
Features loose ends
 
Shipments (hold)
Clean up field names (if we want to)
Public facing data (hold -  deal with it post Seattle)
 
Testing (clean and park)
Panel  memberships – status? Possibly run more reconstructions
Volume arithmetic - status, and park
Outstanding assays -
Results/clinical data extraction
 
Eddi tools (as discussed – launch ASAP – lots of help material to be produced)
