# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 08:16
from __future__ import unicode_literals

from django.db import migrations

def add_outside_eddi_group(apps, schema):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get_or_create(name='Outside Eddi Users')


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_outsideeddiuser'),
    ]

    operations = [
        migrations.RunPython(add_outside_eddi_group, migrations.RunPython.noop)
    ]
