# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_add_outside_eddi_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutsideEddiUser',
        ),
    ]
