# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0001_initial'),
        ('assay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayrun',
            name='inconsistent_replicates',
            field=models.ManyToManyField(to='assay.PanelMembership'),
        ),
        migrations.AddField(
            model_name='assayrun',
            name='visits_missing_from_panel',
            field=models.ManyToManyField(related_name='assay_run_missing_visits', to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='assayrun',
            name='visits_not_in_panel',
            field=models.ManyToManyField(related_name='assay_run_extra_visits', to='cephia.Visit'),
        ),
    ]
