# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0002_auto_20160526_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectavidityresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architectunmodifiedresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bedresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioradaviditycdcresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioradavidityglasgowresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioradavidityjhuresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idev3result',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lagmaximresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lagsediaresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsvitrosdiluentresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsvitrosplasmaresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='luminexcdcresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitrosavidityresult',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
