# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0003_auto_20160406_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='result_treated_SCO',
            new_name='treated_SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='result_untreated_SCO',
            new_name='untreated_SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='result_treated_SCO',
            new_name='treated_SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='result_untreated_SCO',
            new_name='untreated_SCO',
        ),
        migrations.RenameField(
            model_name='architectunmodifiedresult',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='architectunmodifiedresultrow',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='assayresult',
            old_name='result_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='assayresult',
            old_name='result_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='bedresult',
            old_name='result_OD',
            new_name='OD',
        ),
        migrations.RenameField(
            model_name='bedresult',
            old_name='result_ODn',
            new_name='ODn',
        ),
        migrations.RenameField(
            model_name='bedresult',
            old_name='result_calibrator_OD',
            new_name='calibrator_OD',
        ),
        migrations.RenameField(
            model_name='bedresultrow',
            old_name='result_OD',
            new_name='OD',
        ),
        migrations.RenameField(
            model_name='bedresultrow',
            old_name='result_ODn',
            new_name='ODn',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='result_clasification',
            new_name='clasification',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='result_clasification',
            new_name='clasification',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='result_treated_OD',
            new_name='treated_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='result_untreated_OD',
            new_name='untreated_OD',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_GeeniusIndex',
            new_name='GeeniusIndex',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_ctrl_BI',
            new_name='ctrl_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_gp140_BI',
            new_name='gp140_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_gp160_BI',
            new_name='gp160_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_gp36_BI',
            new_name='gp36_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_gp41_BI',
            new_name='gp41_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_p24_BI',
            new_name='p24_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresult',
            old_name='result_p31_BI',
            new_name='p31_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_GeeniusIndex',
            new_name='GeeniusIndex',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_ctrl_BI',
            new_name='ctrl_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_gp140_BI',
            new_name='gp140_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_gp160_BI',
            new_name='gp160_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_gp36_BI',
            new_name='gp36_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_gp41_BI',
            new_name='gp41_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_p24_BI',
            new_name='p24_BI',
        ),
        migrations.RenameField(
            model_name='geeniusresultrow',
            old_name='result_p31_BI',
            new_name='p31_BI',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_conclusion',
            new_name='conclusion',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_conclusion_recalc',
            new_name='conclusion_recalc',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_intermediate',
            new_name='intermediate',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_ratioTM',
            new_name='ratioTM',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_ratioV3',
            new_name='ratioV3',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_tm_OD',
            new_name='tm_OD',
        ),
        migrations.RenameField(
            model_name='idev3result',
            old_name='result_v3_OD',
            new_name='v3_OD',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_conclusion',
            new_name='conclusion',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_conclusion_recalc',
            new_name='conclusion_recalc',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_intermediate',
            new_name='intermediate',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_ratioTM',
            new_name='ratioTM',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_ratioV3',
            new_name='ratioV3',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_tm_OD',
            new_name='tm_OD',
        ),
        migrations.RenameField(
            model_name='idev3resultrow',
            old_name='result_v3_OD',
            new_name='v3_OD',
        ),
        migrations.RenameField(
            model_name='lsvitrosdiluentresult',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='lsvitrosdiluentresultrow',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='lsvitrosplasmaresult',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='lsvitrosplasmaresultrow',
            old_name='result_SCO',
            new_name='SCO',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_LuminexIndex',
            new_name='LuminexIndex',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp120_a',
            new_name='gp120_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp120_n',
            new_name='gp120_n',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp160_a',
            new_name='gp160_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp160_n',
            new_name='gp160_n',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp41_a',
            new_name='gp41_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresult',
            old_name='result_gp41_n',
            new_name='gp41_n',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_LuminexIndex',
            new_name='LuminexIndex',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp120_a',
            new_name='gp120_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp120_n',
            new_name='gp120_n',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp160_a',
            new_name='gp160_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp160_n',
            new_name='gp160_n',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp41_a',
            new_name='gp41_a',
        ),
        migrations.RenameField(
            model_name='luminexcdcresultrow',
            old_name='result_gp41_n',
            new_name='gp41_n',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresult',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresult',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresult',
            old_name='result_treated_SCO',
            new_name='treated_SCO',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresult',
            old_name='result_untreated_SCO',
            new_name='untreated_SCO',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresultrow',
            old_name='result_AI',
            new_name='AI',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresultrow',
            old_name='result_AI_recalc',
            new_name='AI_recalc',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresultrow',
            old_name='result_treated_SCO',
            new_name='treated_SCO',
        ),
        migrations.RenameField(
            model_name='vitrosavidityresultrow',
            old_name='result_untreated_SCO',
            new_name='untreated_SCO',
        ),
        migrations.RemoveField(
            model_name='bedresult',
            name='result_ODn_recalc',
        ),
        migrations.RemoveField(
            model_name='bedresultrow',
            name='result_ODn_recalc',
        ),
        migrations.RemoveField(
            model_name='bedresultrow',
            name='result_calibrator_OD',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='result_GeeniusIndex_recalc',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='result_GeeniusIndex_recalc',
        ),
        migrations.AddField(
            model_name='bedresult',
            name='ODn_reported',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bedresultrow',
            name='ODn_reported',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bedresultrow',
            name='calibrator_OD',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='GeeniusIndex_reported',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='GeeniusIndex_reported',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AlterModelTable(
            name='architectavidityresult',
            table='assayarchitectavidity',
        ),
        migrations.AlterModelTable(
            name='architectunmodifiedresult',
            table='assayarchitectunmodified',
        ),
        migrations.AlterModelTable(
            name='bedresult',
            table='assaybed',
        ),
        migrations.AlterModelTable(
            name='bioradaviditycdcresult',
            table='assaybioradavidity_cdc',
        ),
        migrations.AlterModelTable(
            name='bioradavidityglasgowresult',
            table='assaybioradavidity_glasgow',
        ),
        migrations.AlterModelTable(
            name='bioradavidityjhuresult',
            table='assaybioradavidity_jhu',
        ),
        migrations.AlterModelTable(
            name='geeniusresult',
            table='assaygeenius',
        ),
        migrations.AlterModelTable(
            name='idev3result',
            table='assayidev3',
        ),
        migrations.AlterModelTable(
            name='lsvitrosdiluentresult',
            table='assaylsvitros_diluent',
        ),
        migrations.AlterModelTable(
            name='lsvitrosplasmaresult',
            table='assaylsvitros_plasma',
        ),
        migrations.AlterModelTable(
            name='luminexcdcresult',
            table='assayluminexcdc',
        ),
        migrations.AlterModelTable(
            name='vitrosavidityresult',
            table='assayvitrosavidity',
        ),
    ]
