# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0003_auto_20160609_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectunmodifiedresult',
            name='well',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
