# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0005_auto_20160613_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idev3result',
            name='intermediare',
        ),
        migrations.RemoveField(
            model_name='idev3resultrow',
            name='intermediare',
        ),
        migrations.AddField(
            model_name='idev3result',
            name='intermediaire',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='idev3resultrow',
            name='intermediaire',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
