# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0006_auto_20160613_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayresult',
            name='interpretation',
            field=models.CharField(choices=[(b'recent', b'Recent'), (b'non_recent', b'Non-Recent')], max_length=255, null=True),
        ),
    ]
