# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0007_assayresult_interpretation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeniusresult',
            name='ctrl_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='gp140_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='gp160_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='gp36_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='gp41_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='p24_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='p31_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='GeeniusIndex_reported',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='ctrl_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='gp140_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='gp160_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='gp36_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='gp41_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='p24_BI',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='p31_BI',
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='ctrl_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='gp140_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='gp160_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='gp36_bi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='gp41_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='p24_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='p31_bi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='ctrl_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='gp140_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='gp160_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='gp36_bi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='gp41_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='p24_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geeniusresultrow',
            name='p31_bi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geeniusresultrow',
            name='GeeniusIndex',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
