# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 11:29
from __future__ import unicode_literals

import cephia.fields
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0055_hotfix_for_viral_loads'),
        ('assay', '0008_auto_20160622_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISGlobalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('assay_kit_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('plate_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('test_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen_label', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.CharField(choices=[(b'recent', b'Recent'), (b'non_recent', b'Non-Recent')], max_length=255, null=True)),
                ('exclusion', models.CharField(max_length=255, null=True)),
                ('warning_msg', models.CharField(max_length=255, null=True)),
                ('error_message', models.CharField(max_length=255, null=True)),
                ('classification_weighted_model', models.CharField(max_length=255, null=True)),
                ('classification_unweighted_model', models.CharField(max_length=255, null=True)),
                ('recent_weighted_model', models.NullBooleanField()),
                ('recent_unweighted_model', models.NullBooleanField()),
                ('assay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cephia.Assay')),
                ('assay_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assay.AssayResult')),
                ('assay_run', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assay.AssayRun')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cephia.Laboratory')),
                ('specimen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cephia.Specimen')),
            ],
            options={
                'db_table': 'assay_isglobal',
            },
        ),
        migrations.CreateModel(
            name='ISGlobalResultRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('specimen_label', models.CharField(blank=True, max_length=255, null=True)),
                ('assay', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratory', models.CharField(blank=True, max_length=255, null=True)),
                ('test_date', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('assay_kit_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('plate_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('test_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.CharField(max_length=255, null=True)),
                ('exclusion', models.CharField(max_length=255, null=True)),
                ('classification_weighted_model', models.CharField(max_length=255, null=True)),
                ('classification_unweighted_model', models.CharField(max_length=255, null=True)),
                ('fileinfo', cephia.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cephia.FileInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='panelmembership',
            name='category',
            field=models.CharField(blank=True, choices=[(b'mdri', b'MDRI'), (b'frr', b'FRR'), (b'challenge', b'Challenge'), (b'control', b'Control')], max_length=255),
        ),
    ]
