# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 11:30
from __future__ import unicode_literals

from django.db import migrations

def add_assays(apps, schema_editor):
    model = apps.get_model("cephia", "Assay")

    assay_list = [{'short_name':'ISGlobal',
                   'long_name':'ISGlobal',
                   'developer':'ISGlobal',
                   'description':''},
]

    for assay in assay_list:
        model.objects.create(name=assay['short_name'],
                             long_name=assay['long_name'],
                             developer=assay['developer'],
                             description=assay['description'])



class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0009_auto_20160804_1329'),
    ]

    operations = [
        migrations.RunPython(add_assays, migrations.RunPython.noop)
    ]
