# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0011_auto_20160418_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='treated_SCO',
            new_name='treated_guanidine_SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresult',
            old_name='untreated_SCO',
            new_name='untreated_pbs_SCO',
        ),
        migrations.RenameField(
            model_name='architectavidityresultrow',
            old_name='well_untreated',
            new_name='well_untreated_pbs',
        ),
        migrations.RenameField(
            model_name='architectunmodifiedresult',
            old_name='well_untreated',
            new_name='well',
        ),
        migrations.RenameField(
            model_name='architectunmodifiedresultrow',
            old_name='well_untreated',
            new_name='well',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='treated_OD',
            new_name='treated_DEA_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='untreated_OD',
            new_name='untreated_dilwashsoln_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresult',
            old_name='well_untreated',
            new_name='well_treated_DEA',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='treated_OD',
            new_name='treated_DEA_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='untreated_OD',
            new_name='untreated_dilwashsoln_OD',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='well_treated',
            new_name='well_treated_DEA',
        ),
        migrations.RenameField(
            model_name='bioradaviditycdcresultrow',
            old_name='well_untreated',
            new_name='well_untreated_dilwashsoln',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='treated_OD',
            new_name='treated_urea_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='untreated_OD',
            new_name='untreated_dilwashsoln_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresult',
            old_name='well_untreated',
            new_name='well_treated_urea',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='treated_OD',
            new_name='well_treated_urea',
        ),
        migrations.RenameField(
            model_name='bioradavidityglasgowresultrow',
            old_name='untreated_OD',
            new_name='well_untreated_dilwashsoln',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='treated_OD',
            new_name='treated_DEA_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='untreated_OD',
            new_name='untreated_dilwashsoln_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresult',
            old_name='well_untreated',
            new_name='well_treated_DEA',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='treated_OD',
            new_name='treated_DEA_OD',
        ),
        migrations.RenameField(
            model_name='bioradavidityjhuresultrow',
            old_name='untreated_OD',
            new_name='untreated_dilwashsoln_OD',
        ),
        migrations.RenameField(
            model_name='lagmaximresultrow',
            old_name='well_untreated',
            new_name='well',
        ),
        migrations.RenameField(
            model_name='lagsediaresultrow',
            old_name='well_untreated',
            new_name='well',
        ),
        migrations.RemoveField(
            model_name='architectavidityresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='bedresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='bedresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='bioradaviditycdcresult',
            name='well_treated',
        ),
        migrations.RemoveField(
            model_name='bioradavidityglasgowresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='bioradavidityjhuresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='geeniusresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='geeniusresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='idev3result',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='idev3resultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lagmaximresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lagsediaresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lsvitrosdiluentresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lsvitrosdiluentresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lsvitrosplasmaresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='lsvitrosplasmaresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='luminexcdcresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='luminexcdcresultrow',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='vitrosavidityresult',
            name='well_untreated',
        ),
        migrations.RemoveField(
            model_name='vitrosavidityresultrow',
            name='well_untreated',
        ),
        migrations.AddField(
            model_name='architectavidityresult',
            name='well_treated_guanidine',
            field=models.CharField(max_length=10, blank=True),
        ),
        migrations.AddField(
            model_name='architectavidityresult',
            name='well_untreated_pbs',
            field=models.CharField(max_length=10, blank=True),
        ),
        migrations.AddField(
            model_name='architectavidityresultrow',
            name='well_treated_guanidine',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bioradaviditycdcresult',
            name='well_untreated_dilwashsoln',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bioradavidityglasgowresult',
            name='well_untreated_dilwashsoln',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bioradavidityglasgowresultrow',
            name='treated_urea_OD',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioradavidityglasgowresultrow',
            name='untreated_dilwashsoln_OD',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioradavidityjhuresult',
            name='well_untreated_dilwashsoln',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bioradavidityjhuresultrow',
            name='well_treated_DEA',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='bioradavidityjhuresultrow',
            name='well_untreated_dilwashsoln',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='lagmaximresult',
            name='well',
            field=models.CharField(max_length=10, blank=True),
        ),
        migrations.AddField(
            model_name='lagsediaresult',
            name='well',
            field=models.CharField(max_length=10, blank=True),
        ),
        migrations.AlterField(
            model_name='bioradavidityglasgowresultrow',
            name='AI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bioradavidityglasgowresultrow',
            name='AI_reported',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
