# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0014_auto_20160812_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayrun',
            name='inconsistent_replicates',
            field=models.ManyToManyField(to='assay.PanelMembership'),
        ),
    ]
