# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0015_assayrun_inconsistent_replicates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayrun',
            old_name='contains_visits_outside_panel',
            new_name='contains_visits_not_in_panel',
        ),
    ]
