# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0016_auto_20160812_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectavidityresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='architectunmodifiedresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bedresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bioplexdukeresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bioradaviditycdcresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bioradavidityglasgowresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bioradavidityjhuresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='geeniusresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='idev3resultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='isglobalresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lagmaximresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lagsediaresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lsvitrosdiluentresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lsvitrosplasmaresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='luminexcdcresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='panelmembershiprow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='panelshipmentrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vitrosavidityresultrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
    ]
