# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 10:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0067_set_default_visit_ids_on_assay_results'),
        ('assay', '0017_auto_20160829_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectavidityresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='architectunmodifiedresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='bedresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='bioplexdukeresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='bioradaviditycdcresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='bioradavidityglasgowresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='bioradavidityjhuresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='geeniusresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='idev3result',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='isglobalresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='lagmaximresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='lagsediaresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='lsvitrosdiluentresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='lsvitrosplasmaresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='luminexcdcresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='vitrosavidityresult',
            name='visit',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
    ]
