# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0071_merge'),
        ('assay', '0019_set_default_visit_ids_on_assay_results'),
    ]

    operations = [
        
    ]
