# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 10:21
from __future__ import unicode_literals

import cephia.fields
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0071_auto_20161114_1221'),
        ('assay', '0019_set_default_visit_ids_on_assay_results'),
    ]

    operations = [

    ]
