# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0020_auto_20161114_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customassayresult',
            old_name='classification',
            new_name='result_classification',
        ),
        migrations.RenameField(
            model_name='customassayresultrow',
            old_name='classification',
            new_name='result_classification',
        ),
        migrations.AddField(
            model_name='customassayresult',
            name='result_quantitative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customassayresultrow',
            name='result_quantitative',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
