# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-14 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0021_auto_20161118_1042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bioplexdukeresult',
            table='assay_bioplexduke',
        ),
        migrations.AlterModelTable(
            name='bioplexdukeresultrow',
            table='assay_bioplexduke_row',
        ),
        migrations.AlterModelTable(
            name='customassayresultrow',
            table='assay_custom_row',
        ),
        migrations.AlterModelTable(
            name='isglobalresultrow',
            table='assay_isglobal_row',
        ),
    ]
