# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0020_auto_20161114_1221'),
        ('assay', '0021_customassayresult_customassayresultrow'),
    ]

    operations = [
    ]
