# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0021_customassayresult_customassayresultrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customassayresult',
            name='result_quantitative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customassayresultrow',
            name='result_quantitative',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
