# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0022_auto_20161117_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customassayresult',
            old_name='classification',
            new_name='result_classification',
        ),
        migrations.RenameField(
            model_name='customassayresultrow',
            old_name='classification',
            new_name='result_classification',
        ),
    ]
