# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0023_auto_20161117_1551'),
        ('assay', '0022_merge'),
    ]

    operations = [
    ]
