# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
import cephia.fields
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0032_auto_20160315_1552'),
        ('assay', '0025_auto_20160505_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuminexCDCResult',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('test_date', models.DateField(max_length=255, null=True, blank=True)),
                ('operator', models.CharField(max_length=255, null=True, blank=True)),
                ('assay_kit_lot', models.CharField(max_length=255, null=True, blank=True)),
                ('plate_identifier', models.CharField(max_length=255, null=True, blank=True)),
                ('test_mode', models.CharField(max_length=255, null=True, blank=True)),
                ('specimen_purpose', models.CharField(max_length=255, null=True, blank=True)),
                ('interpretation', models.CharField(max_length=255, null=True)),
                ('exclusion', models.CharField(max_length=255, null=True)),
                ('warning_msg', models.CharField(max_length=255, null=True)),
                ('well_untreated', models.CharField(max_length=10, null=True)),
                ('well_treated', models.CharField(max_length=10, null=True)),
                ('BSA_MFI', models.FloatField(null=True)),
                ('IgG_MFI', models.FloatField(null=True)),
                ('gp120_MFI', models.FloatField(null=True)),
                ('gp160_MFI', models.FloatField(null=True)),
                ('gp41_MFI', models.FloatField(null=True)),
                ('BSA_MFImb', models.FloatField(null=True)),
                ('IgG_MFImb', models.FloatField(null=True)),
                ('gp120_MFImb', models.FloatField(null=True)),
                ('gp160_MFImb', models.FloatField(null=True)),
                ('gp41_MFImb', models.FloatField(null=True)),
                ('calibrator_BSA', models.FloatField(null=True)),
                ('calibrator_IgG', models.FloatField(null=True)),
                ('calibrator_gp120', models.FloatField(null=True)),
                ('calibrator_gp160', models.FloatField(null=True)),
                ('calibrator_gp41', models.FloatField(null=True)),
                ('gp120_MFIn', models.FloatField(null=True)),
                ('gp160_MFIn', models.FloatField(null=True)),
                ('gp41_MFIn', models.FloatField(null=True)),
                ('DEA_treated_BSA_MFI', models.FloatField(null=True)),
                ('DEA_treated_IgG_MFI', models.FloatField(null=True)),
                ('DEA_treated_gp120_MFI', models.FloatField(null=True)),
                ('DEA_treated_gp160_MFI', models.FloatField(null=True)),
                ('DEA_treated_gp41_MFI', models.FloatField(null=True)),
                ('DEA_treated_BSA_MFImb', models.FloatField(null=True)),
                ('DEA_treated_IgG_MFImb', models.FloatField(null=True)),
                ('DEA_treated_gp120_MFImb', models.FloatField(null=True)),
                ('DEA_treated_gp160_MFImb', models.FloatField(null=True)),
                ('DEA_treated_gp41_MFImb', models.FloatField(null=True)),
                ('DEA_treated_gp120_MFIn', models.FloatField(null=True)),
                ('DEA_treated_gp160_MFIn', models.FloatField(null=True)),
                ('DEA_treated_gp41_MFIn', models.FloatField(null=True)),
                ('gp120_AI', models.FloatField(null=True)),
                ('gp160_AI', models.FloatField(null=True)),
                ('gp41_AI', models.FloatField(null=True)),
                ('assay', models.ForeignKey(to='cephia.Assay', null=True)),
                ('assay_result', models.ForeignKey(to='assay.AssayResult', null=True)),
                ('assay_run', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assay.AssayRun', null=True)),
                ('laboratory', models.ForeignKey(to='cephia.Laboratory', null=True)),
                ('specimen', models.ForeignKey(to='cephia.Specimen', null=True)),
            ],
            options={
                'db_table': 'assayluminexcdc',
            },
        ),
        migrations.CreateModel(
            name='LuminexCDCResultRow',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('specimen_label', models.CharField(max_length=255, null=True, blank=True)),
                ('assay', models.CharField(max_length=255, null=True, blank=True)),
                ('laboratory', models.CharField(max_length=255, null=True, blank=True)),
                ('test_date', models.CharField(max_length=255, null=True, blank=True)),
                ('operator', models.CharField(max_length=255, null=True, blank=True)),
                ('assay_kit_lot', models.CharField(max_length=255, null=True, blank=True)),
                ('plate_identifier', models.CharField(max_length=255, null=True, blank=True)),
                ('test_mode', models.CharField(max_length=255, null=True, blank=True)),
                ('specimen_purpose', models.CharField(max_length=255, null=True, blank=True)),
                ('interpretation', models.CharField(max_length=255, null=True)),
                ('exclusion', models.CharField(max_length=255, null=True)),
                ('BSA_MFI', models.CharField(max_length=255, null=True)),
                ('IgG_MFI', models.CharField(max_length=255, null=True)),
                ('gp120_MFI', models.CharField(max_length=255, null=True)),
                ('gp160_MFI', models.CharField(max_length=255, null=True)),
                ('gp41_MFI', models.CharField(max_length=255, null=True)),
                ('BSA_MFImb', models.CharField(max_length=255, null=True)),
                ('IgG_MFImb', models.CharField(max_length=255, null=True)),
                ('gp120_MFImb', models.CharField(max_length=255, null=True)),
                ('gp160_MFImb', models.CharField(max_length=255, null=True)),
                ('gp41_MFImb', models.CharField(max_length=255, null=True)),
                ('calibrator_BSA', models.CharField(max_length=255, null=True)),
                ('calibrator_IgG', models.CharField(max_length=255, null=True)),
                ('calibrator_gp120', models.CharField(max_length=255, null=True)),
                ('calibrator_gp160', models.CharField(max_length=255, null=True)),
                ('calibrator_gp41', models.CharField(max_length=255, null=True)),
                ('gp120_MFIn', models.CharField(max_length=255, null=True)),
                ('gp160_MFIn', models.CharField(max_length=255, null=True)),
                ('gp41_MFIn', models.CharField(max_length=255, null=True)),
                ('DEA_treated_BSA_MFI', models.CharField(max_length=255, null=True)),
                ('DEA_treated_IgG_MFI', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp120_MFI', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp160_MFI', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp41_MFI', models.CharField(max_length=255, null=True)),
                ('DEA_treated_BSA_MFImb', models.CharField(max_length=255, null=True)),
                ('DEA_treated_IgG_MFImb', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp120_MFImb', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp160_MFImb', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp41_MFImb', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp120_MFIn', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp160_MFIn', models.CharField(max_length=255, null=True)),
                ('DEA_treated_gp41_MFIn', models.CharField(max_length=255, null=True)),
                ('gp120_AI', models.CharField(max_length=255, null=True)),
                ('gp160_AI', models.CharField(max_length=255, null=True)),
                ('gp41_AI', models.CharField(max_length=255, null=True)),
                ('fileinfo', cephia.fields.ProtectedForeignKey(to='cephia.FileInfo', on_delete=django.db.models.deletion.PROTECT)),
            ],
            options={
                'db_table': 'luminex_cdc_row',
            },
        ),
    ]
