# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0074_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayresult',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cephia.Visit'),
        ),
    ]
