# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0024_merge'),
        ('assay', '0026_assayresult_visit'),
    ]

    operations = [
    ]
