# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0017_auto_20160217_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictesthistory',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='cephia.Subject'),
        ),
    ]
