# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0019_auto_20160810_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictesthistoryrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
    ]
