# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0002_auto_20170419_1401'),
        ('cephia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='visits',
            field=models.ManyToManyField(related_name='panels', through='assay.PanelMembership', to='cephia.Visit'),
        ),
    ]
