# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0026_subjecteddi_edsc_days_difference'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAliquotRow',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(editable=False, blank=True)),
                ('parent_label', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('aliquot_label', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('volume', models.CharField(max_length=255, null=True, blank=True)),
                ('volume_units', models.CharField(max_length=255, null=True, blank=True)),
                ('number_of_aliquot', models.CharField(max_length=255, null=True, blank=True)),
                ('aliquoting_date_yyyy', models.CharField(max_length=255, null=True, blank=True)),
                ('aliquoting_date_mm', models.CharField(max_length=255, null=True, blank=True)),
                ('aliquoting_date_dd', models.CharField(max_length=255, null=True, blank=True)),
                ('reason', models.CharField(max_length=255, null=True, blank=True)),
                ('specimen_type', models.CharField(max_length=255, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('comment', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.ImportedRowComment', null=True)),
                ('fileinfo', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.FileInfo', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('specimen', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.Specimen', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical aliquot row',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubjectRow',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(editable=False, blank=True)),
                ('subject_label', models.CharField(max_length=255, blank=True)),
                ('source_study', models.CharField(max_length=255, blank=True)),
                ('cohort_entry_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('cohort_entry_date_mm', models.CharField(max_length=255, blank=True)),
                ('cohort_entry_date_dd', models.CharField(max_length=255, blank=True)),
                ('cohort_entry_hiv_status', models.CharField(max_length=255, blank=True)),
                ('country', models.CharField(max_length=255, blank=True)),
                ('last_negative_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('last_negative_date_mm', models.CharField(max_length=255, blank=True)),
                ('last_negative_date_dd', models.CharField(max_length=255, blank=True)),
                ('first_positive_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('first_positive_date_mm', models.CharField(max_length=255, blank=True)),
                ('first_positive_date_dd', models.CharField(max_length=255, blank=True)),
                ('edsc_reported_yyyy', models.CharField(max_length=255, blank=True)),
                ('edsc_reported_mm', models.CharField(max_length=255, blank=True)),
                ('edsc_reported_dd', models.CharField(max_length=255, blank=True)),
                ('fiebig_stage_at_firstpos', models.CharField(max_length=255, blank=True)),
                ('ars_onset_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('ars_onset_date_mm', models.CharField(max_length=255, blank=True)),
                ('ars_onset_date_dd', models.CharField(max_length=255, blank=True)),
                ('date_of_birth_yyyy', models.CharField(max_length=255, blank=True)),
                ('date_of_birth_mm', models.CharField(max_length=255, blank=True)),
                ('date_of_birth_dd', models.CharField(max_length=255, blank=True)),
                ('sex', models.CharField(max_length=255, blank=True)),
                ('transgender', models.CharField(max_length=255, blank=True)),
                ('population_group', models.CharField(max_length=255, blank=True)),
                ('risk_sex_with_men', models.CharField(max_length=255, blank=True)),
                ('risk_sex_with_women', models.CharField(max_length=255, blank=True)),
                ('risk_idu', models.CharField(max_length=255, blank=True)),
                ('subtype', models.CharField(max_length=255, blank=True)),
                ('subtype_confirmed', models.CharField(max_length=255, blank=True)),
                ('aids_diagnosis_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('aids_diagnosis_date_mm', models.CharField(max_length=255, blank=True)),
                ('aids_diagnosis_date_dd', models.CharField(max_length=255, blank=True)),
                ('art_initiation_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('art_initiation_date_mm', models.CharField(max_length=255, blank=True)),
                ('art_initiation_date_dd', models.CharField(max_length=255, blank=True)),
                ('art_interruption_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('art_interruption_date_mm', models.CharField(max_length=255, blank=True)),
                ('art_interruption_date_dd', models.CharField(max_length=255, blank=True)),
                ('art_resumption_date_yyyy', models.CharField(max_length=255, blank=True)),
                ('art_resumption_date_mm', models.CharField(max_length=255, blank=True)),
                ('art_resumption_date_dd', models.CharField(max_length=255, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('comment', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.ImportedRowComment', null=True)),
                ('fileinfo', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.FileInfo', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('subject', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.Subject', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical subject row',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransferInRow',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(editable=False, blank=True)),
                ('specimen_label', models.CharField(max_length=255, null=True, blank=True)),
                ('subject_label', models.CharField(max_length=255, null=True, blank=True)),
                ('drawdate_yyyy', models.CharField(max_length=255, null=True, blank=True)),
                ('drawdate_mm', models.CharField(max_length=255, null=True, blank=True)),
                ('drawdate_dd', models.CharField(max_length=255, null=True, blank=True)),
                ('number_of_containers', models.CharField(max_length=255, null=True, blank=True)),
                ('transfer_date_yyyy', models.CharField(max_length=255, null=True, blank=True)),
                ('transfer_date_mm', models.CharField(max_length=255, null=True, blank=True)),
                ('transfer_date_dd', models.CharField(max_length=255, null=True, blank=True)),
                ('location', models.CharField(max_length=255, null=True, blank=True)),
                ('transfer_reason', models.CharField(max_length=255, null=True, blank=True)),
                ('specimen_type', models.CharField(max_length=255, null=True, blank=True)),
                ('volume', models.CharField(max_length=255, null=True, blank=True)),
                ('volume_units', models.CharField(max_length=255, null=True, blank=True)),
                ('source_study', models.CharField(max_length=255, null=True, blank=True)),
                ('notes', models.CharField(max_length=255, null=True, blank=True)),
                ('roll_up', models.NullBooleanField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('comment', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.ImportedRowComment', null=True)),
                ('fileinfo', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.FileInfo', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('specimen', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.Specimen', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical transfer in row',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransferOutRow',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(editable=False, blank=True)),
                ('specimen_label', models.CharField(max_length=255, null=True, blank=True)),
                ('number_of_containers', models.CharField(max_length=255, null=True, blank=True)),
                ('specimen_type', models.CharField(max_length=255, null=True, blank=True)),
                ('volume', models.CharField(max_length=255, null=True, blank=True)),
                ('volume_units', models.CharField(max_length=255, null=True, blank=True)),
                ('shipped_in_panel', models.CharField(max_length=255, null=True, blank=True)),
                ('shipment_date_dd', models.CharField(max_length=255, null=True, blank=True)),
                ('shipment_date_mm', models.CharField(max_length=255, null=True, blank=True)),
                ('shipment_date_yyyy', models.CharField(max_length=255, null=True, blank=True)),
                ('destination_site', models.CharField(max_length=255, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('comment', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.ImportedRowComment', null=True)),
                ('fileinfo', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.FileInfo', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('specimen', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.Specimen', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical transfer out row',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVisitRow',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('state', models.CharField(max_length=10, choices=[(b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')])),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(editable=False, blank=True)),
                ('subject_label', models.CharField(max_length=255, blank=True)),
                ('visitdate_yyyy', models.CharField(max_length=255, blank=True)),
                ('visitdate_mm', models.CharField(max_length=255, blank=True)),
                ('visitdate_dd', models.CharField(max_length=255, blank=True)),
                ('visit_hivstatus', models.CharField(max_length=255, blank=True)),
                ('source_study', models.CharField(max_length=255, blank=True)),
                ('cd4_count', models.CharField(max_length=255, blank=True)),
                ('vl', models.CharField(max_length=255, blank=True)),
                ('scopevisit_ec', models.CharField(max_length=255, blank=True)),
                ('pregnant', models.CharField(max_length=255, blank=True)),
                ('hepatitis', models.CharField(max_length=255, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('comment', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.ImportedRowComment', null=True)),
                ('fileinfo', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.FileInfo', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('visit', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='cephia.Visit', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical visit row',
            },
        ),
    ]
