# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0031_auto_20160524_1410'),
        ('cephia', '0038_auto_20160517_1406'),
    ]

    operations = [
    ]
