# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:52
from __future__ import unicode_literals

import cephia.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0040_auto_20160525_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_aids_diagnosis', models.NullBooleanField()),
                ('age', models.IntegerField(null=True)),
                ('ever_aids_diagnosis', models.NullBooleanField()),
                ('ever_scope_ec', models.NullBooleanField()),
                ('earliest_visit_date', models.DateField(null=True)),
                ('time_since_cohort_entry', models.IntegerField(null=True)),
                ('time_since_first_draw', models.IntegerField(null=True)),
                ('time_since_first_art', models.IntegerField(null=True)),
                ('time_since_current_art_init', models.IntegerField(null=True)),
                ('time_from_eddi_to_tx', models.IntegerField(null=True)),
                ('visit', cephia.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit')),
            ],
            options={
                'db_table': 'cephia_visit_details',
            },
        ),
    ]
