# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0042_auto_20160620_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitdetail',
            old_name='days_since_first_art_visit',
            new_name='days_since_current_art',
        ),
        migrations.RenameField(
            model_name='visitdetail',
            old_name='after_aids_diagnosis',
            new_name='is_after_aids_diagnosis',
        ),
        migrations.AddField(
            model_name='visitdetail',
            name='days_since_first_art',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
