# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0043_auto_20160627_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetail',
            name='days_from_eddi_to_current_art',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='days_from_eddi_to_first_art',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='days_since_cohort_entry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='days_since_current_art',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='days_since_first_art',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='days_since_first_draw',
            field=models.IntegerField(null=True),
        ),
    ]
