# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0046_auto_20160704_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='specimen_label_type',
            field=models.CharField(blank=True, choices=[(b'aliquot_label', b'Aliquot Label'), (b'root_specimen', b'Root Specimen'), (b'aliquot_base', b'Aliquot Base')], default=b'aliquot_label', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalfileinfo',
            name='specimen_label_type',
            field=models.CharField(blank=True, choices=[(b'aliquot_label', b'Aliquot Label'), (b'root_specimen', b'Root Specimen'), (b'aliquot_base', b'Aliquot Base')], default=b'aliquot_label', max_length=255),
        ),
    ]
