# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0048_auto_20160704_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalfileinfo',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
