# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 13:54
from __future__ import unicode_literals

import cephia.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0008_auto_20160622_1356'),
        ('cephia', '0050_auto_20160706_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='visits',
            field=models.ManyToManyField(related_name='visit', through='assay.PanelMembership', to='cephia.Visit'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='visit',
            field=cephia.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='cephia.Visit'),
        ),
    ]
