# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0051_auto_20160706_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='visits',
            field=models.ManyToManyField(related_name='panels', through='assay.PanelMembership', to='cephia.Visit'),
        ),
    ]
