# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 10:19
from __future__ import unicode_literals

from django.db import migrations

def hotfix_viral_loads(apps, schema):
    Visit = apps.get_model('cephia', 'Visit')
    Subject = apps.get_model('cephia', 'Subject')

    subjects = [
        '235070',
        '2023069',
        '2023077',
        '2100225',
        '4100815525800',
        '4201004689900',
        '11701141180100',
        'CEPH-5297',
        ]

    draw_dates = [
        datetime.datetime(2009,3,21),
        datetime.datetime(2014,6,9),
        datetime.datetime(2015,2,9),
        datetime.datetime(2014,10,14),
        datetime.datetime(2008,12,18),
        datetime.datetime(2010,9,14),
        datetime.datetime(2011,2,15),
        datetime.datetime(2015,5,14),
    ]

    viral_loads = [
        '=32934',
        '=92203',
        '=45',
        '=5714',
        '=7926586',
        '=48451',
        '=146745',
        '=6735',
    ]

    for subject_label, draw_date, vl_reported in zip(subjects, draw_dates, viral_loads):
        subject = Subject.objects.get(subject_label=subject_label)

        visit = subject.visit_set.filter(visit_date=draw_date).first()
        if visit is None:
            raise Exception('Could not find visit for draw_date %s' % draw_date)

        visit.vl_reported = vl_reported
        visit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0054_auto_20160711_1555'),
    ]

    operations = [
        migrations.RunPython(hotfix_viral_loads, migrations.RunPython.noop)
    ]
