# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0057_auto_20160816_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisit',
            name='scopevisit_ec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='scopevisit_ec',
            field=models.BooleanField(default=False),
        ),
    ]
