# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0059_auto_20150820_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annihilationrow',
            name='fileinfo',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='missingtransferoutrow',
            name='fileinfo',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='aliquoting_reason',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='panel_inclusion_criteria',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='source_study',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='spec_type',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='subjectrow',
            name='fileinfo',
        ),
        migrations.RemoveField(
            model_name='transferinrow',
            name='fileinfo',
        ),
        migrations.RemoveField(
            model_name='transferoutrow',
            name='fileinfo',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='study',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='visitrow',
            name='fileinfo',
        ),
        migrations.DeleteModel(
            name='AliquotingReason',
        ),
        migrations.DeleteModel(
            name='AnnihilationRow',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MissingTransferOutRow',
        ),
        migrations.DeleteModel(
            name='PanelInclusionCriteria',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Specimen',
        ),
        migrations.DeleteModel(
            name='SpecimenType',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectRow',
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
        migrations.DeleteModel(
            name='TransferInRow',
        ),
        migrations.DeleteModel(
            name='TransferOutRow',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.DeleteModel(
            name='VisitRow',
        ),
    ]
