# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0060_auto_20160829_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralloadrow',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cephia.Visit'),
        ),
    ]
