# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0061_viralloadrow_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='vl_cephia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='vl_cephia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='vl_reported',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='vl_reported',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
