# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0062_auto_20160829_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquotrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalaliquotrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsubjectrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltransferinrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltransferoutrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvisitrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferinrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferoutrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='viralloadrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitrow',
            name='state',
            field=models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20),
        ),
    ]
