# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 11:43
from __future__ import unicode_literals

import cephia.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0063_auto_20160829_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentStatusUpdateRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'recalled', b'Recalled'), (b'pending', b'Pending'), (b'validated', b'Validated'), (b'imported', b'Imported'), (b'processed', b'Processed'), (b'error', b'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('source_study', models.CharField(blank=True, max_length=255)),
                ('art_initiation_date_yyyy', models.CharField(blank=True, max_length=255)),
                ('art_initiation_date_mm', models.CharField(blank=True, max_length=255)),
                ('art_initiation_date_dd', models.CharField(blank=True, max_length=255)),
                ('art_interruption_date_yyyy', models.CharField(blank=True, max_length=255)),
                ('art_interruption_date_mm', models.CharField(blank=True, max_length=255)),
                ('art_interruption_date_dd', models.CharField(blank=True, max_length=255)),
                ('art_resumption_date_yyyy', models.CharField(blank=True, max_length=255)),
                ('art_resumption_date_mm', models.CharField(blank=True, max_length=255)),
                ('art_resumption_date_dd', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cephia_treatmentstatusupdate_rows',
            },
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_type',
            field=models.CharField(choices=[(b'', b'---------'), (b'aliquot', b'Aliquot'), (b'assay', b'Assay'), (b'diagnostic_test', b'Diagnostic Test'), (b'panel_shipment', b'Panel Shipment'), (b'panel_membership', b'Panel Membership'), (b'protocol_lookup', b'Protocol Lookup'), (b'subject', b'Subject'), (b'test_history', b'Diagnostic Test History'), (b'test_property', b'Diagnostic Test Properties'), (b'transfer_in', b'Transfer In'), (b'transfer_out', b'Transfer Out'), (b'visit', b'Visit'), (b'viral_load', b'Viral Load'), (b'treatment_status_update', b'Treatment Status Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfileinfo',
            name='file_type',
            field=models.CharField(choices=[(b'', b'---------'), (b'aliquot', b'Aliquot'), (b'assay', b'Assay'), (b'diagnostic_test', b'Diagnostic Test'), (b'panel_shipment', b'Panel Shipment'), (b'panel_membership', b'Panel Membership'), (b'protocol_lookup', b'Protocol Lookup'), (b'subject', b'Subject'), (b'test_history', b'Diagnostic Test History'), (b'test_property', b'Diagnostic Test Properties'), (b'transfer_in', b'Transfer In'), (b'transfer_out', b'Transfer Out'), (b'visit', b'Visit'), (b'viral_load', b'Viral Load'), (b'treatment_status_update', b'Treatment Status Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='viralloadrow',
            name='visit',
            field=cephia.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Visit'),
        ),
        migrations.AddField(
            model_name='treatmentstatusupdaterow',
            name='fileinfo',
            field=cephia.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cephia.FileInfo'),
        ),
        migrations.AddField(
            model_name='treatmentstatusupdaterow',
            name='subject',
            field=cephia.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cephia.Subject'),
        ),
    ]
