# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0066_historicalsubjecteddi_historicalvisiteddi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='data_file',
            field=models.FileField(upload_to=b'/home/andrew/id/cephia/cephia/cephia/../../media'),
        ),
    ]
