# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0067_auto_20160923_1027'),
        ('cephia', '0067_set_default_visit_ids_on_assay_results'),
    ]

    operations = [
    ]
