# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 12:26
from __future__ import unicode_literals
from datetime import datetime
from django.db import migrations

def fix_subject(apps, schema):
    lines = [
        "4117600097 2015-3-10",
        "4118000024 2014-11-10",
        "4118000035 2014-6-23",
        "4118000054 2014-11-4",
        "4118000074 2014-12-10",
        "4118000086 2014-7-17",
        "4118000101 2014-7-30",
        "4118000112 2014-12-30",
        "4118000138 2014-6-16",
        "4118000145 2014-11-6",
        "4118000156 2014-8-5",
        "4118000168 2014-12-22",
        "4118000172 2014-8-6",
        "4118000196 2014-6-22",
        "4118000226 2014-5-12",
        "4118000236 2014-11-19",
        "4118000277 2015-1-19",
        "4118000281 2014-11-24",
        "4118000298 2014-6-5",
        "4118000337 2015-4-27",
        "4118000344 2015-1-19",
        "4118000353 2015-7-13",
        "4118000367 2015-8-12",
        "4118000376 2015-8-31",
        "SCOPE1451 2008-12-8",
        "SCOPE1464 2008-7-17",
        "SCOPE1692 2010-8-13",
        "SCOPE1718 2010-10-20",
        "SCOPE1738 2010-12-17",
        "SCOPE1747 2011-3-9",
        "SCOPE1767 2010-10-26",
        "SCOPE1769 2011-3-6",
        "SCOPE1770 2010-8-4",
        "SCOPE1779 2011-5-26",
        "SCOPE1780 2010-11-30",
        "SCOPE1784 2011-7-27",
        "SCOPE1786 2011-8-16",
        "SCOPE1790 2011-9-20",
        "SCOPE1791 2011-8-4",
        "SCOPE1792 2011-9-22",
        "SCOPE2311 2009-7-24",
        "SCOPE2340 2009-2-12",
        "SCOPE2363 2009-11-13",
        "SCOPE2371 2009-7-13",
        "SCOPE2372 2010-1-25",
        "SCOPE2396 2009-8-19",
        "SCOPE2406 2009-9-10",
        "SCOPE2408 2009-9-25",
        "SCOPE3600 2011-9-1",
        "SCOPE3602 2011-1-3",
        "SCOPE3604 2011-11-21",
        "SCOPE3605 2011-5-24",
        "SCOPE3609 2012-1-17",
        "SCOPE3613 2011-12-23",
        "SCOPE3625 2012-3-31",
        "SCOPE3630 2012-3-13",
        "SCOPE3660 2013-1-15",
        "SCOPE3676 2012-12-4",
        "SCOPE3677 2012-10-2"]

    SubjectModel = apps.get_model("cephia", "Subject")
    for i in lines:
        sub, d = i.split(" ")
        subject = SubjectModel.objects.get(subject_label=sub)
        d = datetime.strptime(d, '%Y-%m-%d')
        subject.cohort_entry_date = d.date()
        subject.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0067_set_default_visit_ids_on_assay_results'),
    ]

    operations = [
        migrations.RunPython(fix_subject, migrations.RunPython.noop)
    ]
