# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0068_merge'),
        ('cephia', '0070_fix_visit_details'),
    ]

    operations = [
    ]
