# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 09:28
from __future__ import unicode_literals

import cephia.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0071_merge'),
    ]

    operations = [
        
    ]
