# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0071_auto_20161114_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='data_file',
            field=models.FileField(upload_to=b'/home/andrew/id/cephia/cephia/cephia/../../media'),
        ),
    ]
