# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0072_auto_20161118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='viral_load_offset',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='viral_load_offset',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
