# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0072_auto_20161111_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cephiauser',
            options={'permissions': [('can_upload_panel_data', 'Can upload memberships and shipments'), ('can_upload_results', 'Can upload results'), ('can_upload_clinical_data', 'Can upload subjects and visits'), ('can_upload_eddi_data', 'Can upload diagnostic data'), ('can_upload_specimen_data', 'Can upload aliquot, transfer in, transfer out'), ('can_purge_assay_results', 'Can purge assay results'), ('can_purge_assay_runs', 'Can purge assay runs')]},
        ),
    ]
