# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0072_auto_20161114_1257'),
        ('cephia', '0071_merge'),
    ]

    operations = [
    ]
