# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0073_auto_20161116_1407'),
        ('cephia', '0073_merge'),
    ]

    operations = [
    ]
