# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0073_auto_20161129_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisit',
            name='viral_load_offset',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='visit',
            name='viral_load_offset',
            field=models.IntegerField(default=None),
        ),
    ]
