# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephia', '0074_cephiauser_password_reset_token'),
        ('cephia', '0075_auto_20161202_1710'),
    ]

    operations = [
    ]
