# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0002_auto_20160927_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistoryfile',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
