# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0003_testhistoryfile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistoryfile',
            name='data_file',
            field=models.FileField(upload_to='/home/andrew/id/cephia/cephia/cephia/../../mediaoutside_eddi_uploads'),
        ),
    ]
