# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0004_auto_20160927_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistoryfile',
            name='data_file',
            field=models.FileField(upload_to='/home/andrew/id/cephia/cephia/cephia/../../media/outside_eddi_uploads'),
        ),
    ]
