# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0021_historicaldiagnostictest_historicaldiagnostictesthistory_historicalprotocollookup_historicaltestprop'),
        ('cephia', '0067_auto_20160923_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outside_eddi', '0005_auto_20160927_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOutisdeEddiDiagnosticTestHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('test_date', models.DateField(null=True)),
                ('adjusted_date', models.DateField(null=True)),
                ('test_result', models.CharField(max_length=15, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cephia.Subject')),
                ('test', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagnostics.DiagnosticTest')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical outisde eddi diagnostic test history',
            },
        ),
        migrations.CreateModel(
            name='OutisdeEddiDiagnosticTestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(null=True)),
                ('adjusted_date', models.DateField(null=True)),
                ('test_result', models.CharField(max_length=15, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outside_eddi_test_history', to='cephia.Subject')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.DiagnosticTest')),
            ],
            options={
                'db_table': 'outside_eddi_diagnostic_test_history',
            },
        ),
    ]
