# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0006_historicaloutisdeeddidiagnostictesthistory_outisdeeddidiagnostictesthistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalOutisdeEddiDiagnosticTestHistory',
            new_name='HistoricalOutsideEddiDiagnosticTestHistory',
        ),
        migrations.RenameModel(
            old_name='OutisdeEddiDiagnosticTestHistory',
            new_name='OutsideEddiDiagnosticTestHistory',
        ),
        migrations.AlterModelOptions(
            name='historicaloutsideeddidiagnostictesthistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical outside eddi diagnostic test history'},
        ),
    ]
