# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0007_auto_20160927_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'outside_eddi_user_studies',
            },
        ),
    ]
