# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0009_userstudies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudies',
            name='user',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
