# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0010_auto_20161004_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
