# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outside_eddi', '0011_auto_20161004_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstudies',
            name='user',
        ),
        migrations.AlterField(
            model_name='testhistoryfile',
            name='data_file',
            field=models.FileField(upload_to='uploads/outside_eddi_uploads'),
        ),
        migrations.DeleteModel(
            name='UserStudies',
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set([('name', 'user')]),
        ),
    ]
