# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0013_historicaloutsideeddidiagnostictest_historicaloutsideedditestpropertyestimate_outsideeddidiagnostict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='test',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
    ]
