# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0014_auto_20161006_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPropertyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('test', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiDiagnosticTest')),
            ],
        ),
        migrations.AddField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='outsideedditestpropertyestimate',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outsideedditestpropertyestimate',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testpropertymapping',
            name='test_property',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiTestPropertyEstimate'),
        ),
    ]
