# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0015_auto_20161006_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='variance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outsideedditestpropertyestimate',
            name='variance',
            field=models.IntegerField(null=True),
        ),
    ]
