# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outside_eddi', '0016_auto_20161007_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpropertymapping',
            name='user',
            field=lib.fields.ProtectedForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
