# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 14:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0017_testpropertymapping_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpropertymapping',
            name='test',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
        migrations.AlterField(
            model_name='testpropertymapping',
            name='test_property',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiTestPropertyEstimate'),
        ),
    ]
