# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0020_historicaloutsideeddiprotocollookup_outsideeddidiagnostictesthistoryrow_outsideeddiprotocollookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='variance',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='variance',
        ),
    ]
