# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0021_auto_20161019_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='user',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
