# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0022_auto_20161019_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='foursigma_diagnostic_delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='foursigma_diagnostic_delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
