# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0025_auto_20161020_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideeddidiagnostictest',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outsideeddidiagnostictest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
