# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0027_edditable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testpropertymapping',
            unique_together=set([('code', 'user')]),
        ),
    ]
