# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0028_auto_20161024_1222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outsideeddidiagnostictest',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterModelTable(
            name='outsideeddidiagnostictest',
            table=None,
        ),
    ]
