# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0029_auto_20161024_1559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outsideeddidiagnostictest',
            table='outside_eddi_diagnostic_tests',
        ),
    ]
