# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0030_auto_20161024_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
    ]
