# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outside_eddi', '0032_auto_20161026_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOutsideEddiFileInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_file', models.TextField(max_length=100)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('error', 'Error')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical outside eddi file info',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOutsideEddiSubject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject_label', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ep_ddi', models.DateField(blank=True, null=True)),
                ('lp_ddi', models.DateField(blank=True, null=True)),
                ('interval_size', models.IntegerField(blank=True, null=True)),
                ('edsc_days_difference', models.IntegerField(blank=True, null=True)),
                ('eddi', models.DateField(blank=True, null=True)),
                ('recalculate', models.BooleanField(default=False)),
                ('eddi_type', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical outside eddi subject',
            },
        ),
        migrations.CreateModel(
            name='OutsideEddiFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=b'/home/andrew/id/cephia/cephia/cephia/../../media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('error', 'Error')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutsideEddiSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_label', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ep_ddi', models.DateField(blank=True, null=True)),
                ('lp_ddi', models.DateField(blank=True, null=True)),
                ('interval_size', models.IntegerField(blank=True, null=True)),
                ('edsc_days_difference', models.IntegerField(blank=True, null=True)),
                ('eddi', models.DateField(blank=True, null=True)),
                ('recalculate', models.BooleanField(default=False)),
                ('eddi_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='edditable',
            name='test_file',
        ),
        migrations.RemoveField(
            model_name='edditable',
            name='user',
        ),
        migrations.DeleteModel(
            name='OutsideEddiAssay',
        ),
        migrations.RemoveField(
            model_name='outsideeddicountry',
            name='region',
        ),
        migrations.DeleteModel(
            name='OutsideEddiEthnicity',
        ),
        migrations.DeleteModel(
            name='OutsideEddiLaboratory',
        ),
        migrations.DeleteModel(
            name='OutsideEddiLocation',
        ),
        migrations.DeleteModel(
            name='OutsideEddiSpecimenType',
        ),
        migrations.DeleteModel(
            name='OutsideEddiStudy',
        ),
        migrations.DeleteModel(
            name='OutsideEddiSubtype',
        ),
        migrations.DeleteModel(
            name='EDDITable',
        ),
        migrations.DeleteModel(
            name='OutsideEddiCountry',
        ),
        migrations.DeleteModel(
            name='OutsideEddiRegion',
        ),
    ]
