# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 10:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0034_auto_20161026_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddidiagnostictesthistory',
            name='test',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
        migrations.AddField(
            model_name='outsideeddidiagnostictesthistory',
            name='test',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiDiagnosticTest'),
        ),
    ]
