# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0035_auto_20161026_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestHistoryFile',
        ),
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='data_file',
            field=models.FileField(upload_to='uploads/outside_eddi_uploads'),
        ),
    ]
