# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0040_auto_20161026_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='data_file',
            field=models.FileField(upload_to='/home/andrew/id/cephia/cephia/cephia/../../media/outside_eddi_uploads'),
        ),
    ]
