# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0041_auto_20161026_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='protocol',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='test_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='test_result',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='test_source',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='protocol',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='test_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='test_result',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='test_source',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
