# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0042_auto_20161026_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='test_source',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='test_source',
        ),
        migrations.AlterField(
            model_name='historicaloutsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('error', 'Error')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
