# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 08:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0043_auto_20161028_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='data_file',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outside_eddi.OutsideEddiFileInfo'),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='data_file',
            field=lib.fields.ProtectedForeignKey(default=39L, on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiFileInfo'),
            preserve_default=False,
        ),
    ]
