# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0044_auto_20161028_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('error', 'Error')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('error', 'Error')], default='pending', max_length=15),
        ),
    ]
