# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0045_auto_20161028_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('mapped', 'Mapped'), ('error', 'Error')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('validated', 'Validated'), ('needs_mapping', 'Needs Mapping'), ('mapped', 'Mapped'), ('error', 'Error')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='outsideeddisubject',
            name='data_file',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='outside_eddi.OutsideEddiFileInfo'),
        ),
    ]
