# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0047_auto_20161031_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideeddifileinfo',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='outsideeddifileinfo',
            name='deleted',
        ),
    ]
