# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0048_auto_20161031_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddifileinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outsideeddifileinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
