# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0049_auto_20161031_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpropertymapping',
            name='code',
            field=models.CharField(max_length=25),
        ),
    ]
