# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 14:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0050_auto_20161031_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='test_result',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='test_result',
        ),
        migrations.AddField(
            model_name='historicaloutsideeddidiagnostictesthistory',
            name='data_file',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outside_eddi.OutsideEddiFileInfo'),
        ),
        migrations.AddField(
            model_name='outsideeddidiagnostictesthistory',
            name='data_file',
            field=lib.fields.ProtectedForeignKey(default=72, on_delete=django.db.models.deletion.PROTECT, related_name='test_history', to='outside_eddi.OutsideEddiFileInfo'),
            preserve_default=False,
        ),
    ]
