# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0053_auto_20161101_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideeddidiagnostictesthistory',
            name='test',
        ),
        migrations.RemoveField(
            model_name='outsideeddidiagnostictesthistory',
            name='test',
        ),
        migrations.AddField(
            model_name='historicaloutsideeddidiagnostictesthistory',
            name='test_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddidiagnostictesthistory',
            name='test_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
