# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outside_eddi', '0054_auto_20161101_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOutsideEddiSubjectEDDI',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ep_ddi', models.DateField(blank=True, null=True)),
                ('lp_ddi', models.DateField(blank=True, null=True)),
                ('interval_size', models.IntegerField(blank=True, null=True)),
                ('edsc_days_difference', models.IntegerField(blank=True, null=True)),
                ('eddi', models.DateField(blank=True, null=True)),
                ('recalculate', models.BooleanField(default=False)),
                ('eddi_type', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical outside eddi subject eddi',
            },
        ),
        migrations.CreateModel(
            name='OutsideEddiSubjectEDDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_ddi', models.DateField(blank=True, null=True)),
                ('lp_ddi', models.DateField(blank=True, null=True)),
                ('interval_size', models.IntegerField(blank=True, null=True)),
                ('edsc_days_difference', models.IntegerField(blank=True, null=True)),
                ('eddi', models.DateField(blank=True, null=True)),
                ('recalculate', models.BooleanField(default=False)),
                ('eddi_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'outside_eddi_subject_eddi',
            },
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='eddi',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='eddi_type',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='edsc_days_difference',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='ep_ddi',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='interval_size',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='lp_ddi',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='recalculate',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='eddi',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='eddi_type',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='edsc_days_difference',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='ep_ddi',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='interval_size',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='lp_ddi',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='recalculate',
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='subject_eddi',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outside_eddi.OutsideEddiSubjectEDDI'),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='subject_eddi',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outside_eddi.OutsideEddiSubjectEDDI'),
        ),
    ]
