# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0055_auto_20161101_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='edsc_reported',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='edsc_reported',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
