# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0056_auto_20161101_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideeddisubjecteddi',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideeddisubject',
            name='subject_eddi',
        ),
        migrations.RemoveField(
            model_name='outsideeddisubject',
            name='subject_eddi',
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='eddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='edsc_days_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='ep_ddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='interval_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='lp_ddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='recalculate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='eddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='edsc_days_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='ep_ddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='interval_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='lp_ddi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='recalculate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalOutsideEddiSubjectEDDI',
        ),
        migrations.DeleteModel(
            name='OutsideEddiSubjectEDDI',
        ),
    ]
