# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0057_auto_20161108_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddifileinfo',
            name='file_name',
            field=models.CharField(default='placeholder', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsideeddifileinfo',
            name='file_name',
            field=models.CharField(default='placeholder', max_length=150),
            preserve_default=False,
        ),
    ]
