# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0059_auto_20170120_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='estimate_type',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='time0_ref',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='estimate_type',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='outsideedditestpropertyestimate',
            name='time0_ref',
        ),
    ]
