# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0060_auto_20170120_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutsideeddisubject',
            name='rand_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsideeddisubject',
            name='rand_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
