# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0061_auto_20170124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideeddisubject',
            name='rand_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outsideeddisubject',
            name='rand_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
