# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0064_auto_20170127_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpropertymapping',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
