# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0065_auto_20170127_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='diagnostic_delay_iqr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloutsideedditestpropertyestimate',
            name='diagnostic_delay_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='diagnostic_delay_iqr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outsideedditestpropertyestimate',
            name='diagnostic_delay_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
