# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_eddi', '0066_auto_20170130_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutsideeddidiagnostictest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaloutsideeddidiagnostictesthistory',
            name='test_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloutsideeddifileinfo',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outsideeddidiagnostictest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outsideeddidiagnostictesthistory',
            name='test_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outsideeddifileinfo',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testpropertymapping',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
