# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0003_auto_20170511_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idttestpropertyestimate',
            name='diagnostic_delay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
