# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models

def populate_initial_emails(apps, schema):
    IDTAllowedRegistrationEmails = apps.get_model('infection_dating_tool', 'IDTAllowedRegistrationEmails')
    emails = ['alexwelte@sun.ac.za', 'andrew.powrie@gmail.com', 'andrew@impd.co.za', 'eduardgrebe@sun.ac.za']

    for email in emails:
        email = IDTAllowedRegistrationEmails.objects.create(email=email)

class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0003_idtallowedregistrationemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtallowedregistrationemails',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(populate_initial_emails, migrations.RunPython.noop)
    ]
