# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0004_auto_20170511_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='idttestpropertyestimate',
            name='detection_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
