# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0007_idtdiagnostictest_selected_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idtdiagnostictest',
            name='selected_category',
        ),
    ]
