# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0009_auto_20170511_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRateEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_rate', models.FloatField()),
                ('user', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
