# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0012_infectiousperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectiousperiod',
            name='infectious_period_input',
            field=models.FloatField(null=True, verbose_name='Start of infectious period'),
        ),
        migrations.AlterField(
            model_name='infectiousperiod',
            name='origin_viral_load',
            field=models.FloatField(null=True, verbose_name='Viral load at origin/zero'),
        ),
        migrations.AlterField(
            model_name='infectiousperiod',
            name='viral_load',
            field=models.FloatField(null=True, verbose_name='Viral load at start of infectious period'),
        ),
    ]
