# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 13:43
from __future__ import unicode_literals

from django.db import migrations

def create_global_infectious_period(apps, schema):
    InfectiousPeriodModel = apps.get_model("infection_dating_tool", "InfectiousPeriod")
    InfectiousPeriodModel.objects.create(
        infectious_period=-7.7113428695314825,
        infectious_period_input=-7.7,
        viral_growth_rate=0.35,
        origin_viral_load=1.0,
        viral_load=0.002
    )

class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0013_auto_20170627_1601'),
    ]

    operations = [
        migrations.RunPython(create_global_infectious_period, migrations.RunPython.noop)
    ]
