# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0016_auto_20170704_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='idttestpropertyestimate',
            name='diagnostic_delay_sigma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
