# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infection_dating_tool', '0019_auto_20170706_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidualRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residual_risk', models.FloatField()),
                ('infectious_period', models.FloatField()),
                ('infectious_period_input', models.FloatField(null=True, verbose_name='Start of infectious period')),
                ('viral_growth_rate', models.FloatField(null=True)),
                ('origin_viral_load', models.FloatField(null=True, verbose_name='Viral load at origin/zero')),
                ('viral_load', models.FloatField(null=True, verbose_name='Viral load at start of infectious period')),
                ('graph_file_probability', models.FileField(max_length=255, null=True, upload_to='graphs')),
                ('graph_file_donations', models.FileField(max_length=255, null=True, upload_to='graphs')),
                ('user', lib.fields.OneToOneOrNoneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idt_residual_risk',
            },
        ),
        migrations.RemoveField(
            model_name='infectiousperiod',
            name='user',
        ),
        migrations.AlterField(
            model_name='variabilityadjustment',
            name='adjustment_factor',
            field=models.FloatField(default=0.0, verbose_name='Intersubject variability adjustment factor (SDs)'),
        ),
        migrations.DeleteModel(
            name='InfectiousPeriod',
        ),
    ]
