# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0021_auto_20170913_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residualrisk',
            name='upper_limit',
            field=models.FloatField(default=0),
        ),
    ]
