# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 10:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0021_auto_20170912_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='residualrisk',
            name='negative_test',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negative', to='infection_dating_tool.IDTDiagnosticTest'),
        ),
        migrations.AddField(
            model_name='residualrisk',
            name='positive_test',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positive', to='infection_dating_tool.IDTDiagnosticTest'),
        ),
        migrations.AddField(
            model_name='residualrisk',
            name='screening_test',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening', to='infection_dating_tool.IDTDiagnosticTest'),
        ),
    ]
