# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0022_auto_20170912_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='residualrisk',
            name='residual_risk_input',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
