# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-15 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0023_auto_20181115_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='credibilityinterval',
            name='alpha',
            field=models.FloatField(default=0.05, verbose_name='Significance level (alpha) for credibility intervals'),
        ),
        migrations.AddField(
            model_name='credibilityinterval',
            name='calculate_ci',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credibilityinterval',
            name='user',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='credibilityinterval',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='credibilityinterval',
            name='adjustment_factor',
        ),
    ]
