# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0024_residualrisk_upper_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='residualrisk',
            name='choice',
            field=models.CharField(choices=[('estimates', 'Estimates'), ('data', 'Data'), ('supply', 'Supply')], default='estimates', max_length=255),
        ),
    ]
