# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0025_residualrisk_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='residualrisk',
            name='confirmed_transmissions',
            field=models.IntegerField(null=True),
        ),
    ]
