# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-15 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0026_idtdiagnostictesthistory_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idtsubject',
            name='edsc_days_difference',
        ),
        migrations.RemoveField(
            model_name='idtsubject',
            name='edsc_reported',
        ),
    ]
