# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0026_residualrisk_confirmed_transmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='residualrisk',
            name='ci_lower_bound',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='residualrisk',
            name='ci_upper_bound',
            field=models.FloatField(null=True),
        ),
    ]
