# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0027_auto_20181115_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtdiagnostictesthistory',
            name='diagnostic_delay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
