# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_dating_tool', '0027_auto_20170913_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residualrisk',
            name='ci_lower_bound',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residualrisk',
            name='ci_upper_bound',
            field=models.FloatField(default=0, null=True),
        ),
    ]
